version: '3'
networks:
  lnmp-net:
    driver: bridge
services:

  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www/docker_lnmp_swoole/www:/usr/share/nginx/html
      - /www/docker_lnmp_swoole/nginx/conf.d:/etc/nginx/conf.d
      - /www/docker_lnmp_swoole/nginx/logs:/var/log/nginx
    depends_on:
      - php
      - swoole
    restart: always
    networks:
      - lnmp-net
  php:
    container_name: php
    build:
      context: ./php/images # 指定上下文
      dockerfile: Dockerfile.swoole # 指定 Dockerfile
    volumes:
      - /www/docker_lnmp_swoole/www:/usr/share/nginx/html
      - /www/docker_lnmp_swoole/php/logs:/usr/local/var/log
    restart: always
    networks:
      - lnmp-net
  swoole:
    image: "twosee/swoole-coroutine"
    ports:
      - "8888:9501"
      - "9501:9501"
    volumes:
      - /www/docker_lnmp_swoole/www/swoole:/app/src:rw
    restart: always
    command: php /app/src/server.php start
    networks:
      - lnmp-net
