version: '3'
networks:
  lnmp-net:
    driver: bridge
services:

  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www/docker_lnmp_swoole/www:/usr/share/nginx/html
      - /www/docker_lnmp_swoole/nginx/conf.d:/etc/nginx/conf.d
      - /www/docker_lnmp_swoole/nginx/logs:/var/log/nginx
    depends_on:
      - php
    restart: always
    networks:
      - lnmp-net
  php:
    container_name: php
    build:
      context: ./php/images # 指定上下文
      dockerfile: Dockerfile.swoole # 指定 Dockerfile
    restart: always
    networks:
      - lnmp-net
