version: '3'
networks:
  lnmp-net:
    driver: bridge
services:

  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      - 80:80
      - 443:443
      - 10000:10000
    volumes:
      - $PWD/www:/usr/share/nginx/html
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/logs:/var/log/nginx
    depends_on:
      - php74
    restart: always
    networks:
      - lnmp-net
  php74:
    container_name: php74
    build:
      context: ./php/images # 指定上下文
      dockerfile: Dockerfile.swoole # 指定 Dockerfile
    volumes:
      - $PWD/www:/usr/share/nginx/html
    restart: always
    networks:
      - lnmp-net
  swoole:
    image: "twosee/swoole-coroutine"
    ports:
      - "8888:9501"
      - "9501:9501"
      - "9502:9502"
    volumes:
      - $PWD/www/swoole:/app/src:rw
    restart: always
    command: php /app/src/server.php start
    networks:
      - lnmp-net

